language: node_js
node_js: stable

cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install

# before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "googtech"
  - git config user.email "hi@goog.tech"
  - git add .
  - git commit -m ":rocket:update blog"
  - git push --force --quiet "https://${YUBUNTU0109_TOKEN}@${GH_REF}" master:master

# E: Build LifeCycle
branches:
  only:
    - HexoBackup
env:
 global:
   - GH_REF: github.com/GoogTech/GoogTech.github.io.git
